wikipedia:
  url: "http://en.wikipedia.org"
  ssl: false
  name: "Wikipedia"
  use_memcache: true
  memcache_hosts:
    - "localhost:11211"
  cache_prefix: "wikipedia-dev"
  type: json
  random_setting: "custom config settings here"
#  auth_key: "SOME AUTH KEY"
